# Generated by Django 4.1.2 on 2022-10-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kategori',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='buku',
            old_name='Kategori',
            new_name='category',
        ),
    ]
