# Generated by Django 4.1.2 on 2022-12-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0002_rename_kategori_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=150)),
                ('pubDate', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('thumbnail', models.CharField(max_length=150)),
            ],
        ),
    ]
